apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uh9bmpbl6-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b2ac4fd128.lzyh.p3.openshiftapps.com/rhtap/rhtap-qe:e60d0459b002d9763346639da508df42880f5494@sha256:a08a0ca56c8ed4c6c81631d06380688709771c7156172a304b795a55bc3b8764
          name: container-image
